name: Python Package Version Check
description: >
    Parses pyproject.toml, checks package index, and sets outputs to signal if a local version needs publishing.

inputs:
  path:
    description: Path to the pyproject.toml to inspect.
    required: false
    default: pyproject.toml

  index:
    description: Host name of the package index to check.
    required: false
    default: "pypi.org"

runs:
  using: composite
  steps:
    - name: Check package version
      id: export
      shell: bash
      run: |
        "${{ github.action_path }}/entrypoint.py" \
        "${{ inputs.path }}" \
        "${{ inputs.index }}"

outputs:
  current_version_exists:
    description: true if the version exists in the index.
    value: ${{ steps.export.outputs.current_version_exists }}
  package_version:
    description: Version string extracted from pyproject.toml.
    value: ${{ steps.export.outputs.package_version }}
  package_name:
    description: Name of the package extracted from pyproject.toml.
    value: ${{ steps.export.outputs.package_name }}

branding:
  icon: package
  color: yellow