name: Python Package Version Check
description: >
    Parses pyproject.toml, checks package indexes, and sets env vars to signal if a local version needs publishing.

inputs:
  path:
    description: Path to the pyproject.toml to inspect.
    required: false
    default: pyproject.toml

  indexes:
    description: |
      (Optional) Space-separated list of index host names.
    required: false
    default: "pypi.org"

runs:
  using: composite
  steps:
    - name: Check package version
      id: run-check
      shell: bash
      run: |
        python "${{ github.action_path }}/entrypoint.py" \
               "${{ inputs.path }}" \
               ${{ inputs.indexes }}

branding:
  icon: package
  color: yellow