name: Release
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']   # e.g. v2.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write                # needed for tag moves
    steps:
      - uses: actions/checkout@v4

      # 1. Create a GitHub Release from the tag
      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true

      # 2. Move the *major* tag (v2) to this commit
      - name: Update major tag
        env:
          TAG: ${{ github.ref_name }}           # v2.0.0
          GH_TOKEN: ${{ github.token }}
        run: |
          major=${TAG%%.*}                      # → v2
          git tag -f "$major" "$TAG"
          git push -f origin "$major"
