name: test
on:
  pull_request:
  push:
    branches: [main]
env:
  PYTHONWARNINGS: "ignore"     # silence urllib warnings

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Self-integration test
        id: action-test
        uses: ./
        with:
          path: tests/pyproject.toml
          indexes: "pypi.org"